export type User = {
  id: number;
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  phone?: string | null;
  countryOfCitizenship?: string | null;
  dateOfBirth?: string | null;
  preferredPronouns?: string | null;
  emergencyContactName?: string | null;
  emergencyContactRelationship?: string | null;
  emergencyContactPhone?: string | null;
  emergencyContactEmail?: string | null;
  arrivalDate?: string | null;
  departureDate?: string | null;
  dietaryRestrictions?: string | null;
  allergies?: string | null;
  medicalNotes?: string | null;
  whatsappHandle?: string | null;
  facebookProfileUrl?: string | null;
  instagramProfileUrl?: string | null;
  discoverySource?: string | null;
  profilePhotoPath?: string | null;
  profilePhotoUrl?: string | null;
  badgeName?: string | null;
  badgePrefixEmoji?: string | null;
  badgeSuffixEmoji?: string | null;
  requestedUserType?: string | null;
  affiliateCommissionRate?: number | null;
  financeVendorId?: number | null;
  userTypeId?: number;
  userTypeSlug?: string | null;
  userTypeName?: string | null;
  createdAt: Date;
  updatedAt: Date;
  createdBy: number;
  updatedBy: number;
  status: boolean;
  approved?: boolean;
  approvedAt?: Date | string | null;
  approvedBy?: number | null;
  approvalRevokedAt?: Date | string | null;
  approvalRevokedBy?: number | null;
  deactivatedAt?: Date | string | null;
  deactivatedBy?: number | null;
  reactivatedAt?: Date | string | null;
  reactivatedBy?: number | null;
  staffType?: 'volunteer' | 'long_term';
  livesInAccom?: boolean;
  shiftRoleIds?: number[];
};

