export type User = {
  id: number;
  username: string;
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  phone?: string | null;
  countryOfCitizenship?: string | null;
  dateOfBirth?: string | null;
  preferredPronouns?: string | null;
  emergencyContactName?: string | null;
  emergencyContactRelationship?: string | null;
  emergencyContactPhone?: string | null;
  emergencyContactEmail?: string | null;
  arrivalDate?: string | null;
  departureDate?: string | null;
  dietaryRestrictions?: string | null;
  allergies?: string | null;
  medicalNotes?: string | null;
  whatsappHandle?: string | null;
  facebookProfileUrl?: string | null;
  instagramProfileUrl?: string | null;
  discoverySource?: string | null;
  profilePhotoPath?: string | null;
  profilePhotoUrl?: string | null;
  userTypeId?: number;
  createdAt: Date;
  updatedAt: Date;
  createdBy: number;
  updatedBy: number;
  status: boolean;
  staffType?: 'volunteer' | 'long_term';
  livesInAccom?: boolean;
  shiftRoleIds?: number[];
};
