import type { QueryInterface } from 'sequelize'; import { DataTypes, Op } from 'sequelize';
type Params={context:QueryInterface};
export async function up({context:qi}:Params):Promise<void>{const transaction=await qi.sequelize.transaction();try{
  await qi.createTable('inventory_fulfillments',{id:{type:DataTypes.INTEGER,autoIncrement:true,primaryKey:true},inventory_item_id:{type:DataTypes.INTEGER,allowNull:false,references:{model:'inventory_items',key:'id'}},addon_id:{type:DataTypes.INTEGER,allowNull:false,references:{model:'addons',key:'id'}},booking_id:{type:DataTypes.INTEGER,allowNull:true,references:{model:'bookings',key:'id'}},counter_id:{type:DataTypes.INTEGER,allowNull:true,references:{model:'counters',key:'id'}},quantity:{type:DataTypes.DECIMAL(14,3),allowNull:false},status:{type:DataTypes.STRING(30),allowNull:false,defaultValue:'waiting_stock'},delivery_method:{type:DataTypes.STRING(20),allowNull:false,defaultValue:'mail'},recipient_name:{type:DataTypes.STRING(180),allowNull:false},email:{type:DataTypes.STRING(180),allowNull:true},phone:{type:DataTypes.STRING(80),allowNull:true},address:{type:DataTypes.TEXT,allowNull:true},size:{type:DataTypes.STRING(80),allowNull:true},tracking_number:{type:DataTypes.STRING(160),allowNull:true},fulfilled_at:{type:DataTypes.DATE,allowNull:true},postage_finance_transaction_id:{type:DataTypes.INTEGER,allowNull:true,references:{model:'finance_transactions',key:'id'}},notes:{type:DataTypes.TEXT,allowNull:true},created_by:{type:DataTypes.INTEGER,allowNull:false,references:{model:'users',key:'id'}},updated_by:{type:DataTypes.INTEGER,allowNull:true,references:{model:'users',key:'id'}},created_at:{type:DataTypes.DATE,allowNull:false,defaultValue:DataTypes.NOW},updated_at:{type:DataTypes.DATE,allowNull:false,defaultValue:DataTypes.NOW}},{transaction});
  await qi.addColumn('inventory_movements','fulfillment_id',{type:DataTypes.INTEGER,allowNull:true,references:{model:'inventory_fulfillments',key:'id'}},{transaction});
  await qi.addIndex('inventory_movements',['fulfillment_id'],{name:'inventory_movements_fulfillment_unique',unique:true,where:{fulfillment_id:{[Op.ne]:null}},transaction});
  await qi.addIndex('inventory_fulfillments',['status','created_at'],{name:'inventory_fulfillments_queue_idx',transaction}); await transaction.commit();
}catch(e){await transaction.rollback();throw e;}}
export async function down({context:qi}:Params):Promise<void>{const transaction=await qi.sequelize.transaction();try{await qi.removeColumn('inventory_movements','fulfillment_id',{transaction});await qi.dropTable('inventory_fulfillments',{transaction});await transaction.commit();}catch(e){await transaction.rollback();throw e;}}
