export const PAGE_SLUGS = {
  dashboard: "dashboard",
  bookings: "bookings",
  bookingsManifest: "bookings-manifest",
  guests: "guests",
  channels: "settings-channels",
  counters: "counters",
  products: "settings-products",
  productTypes: "settings-product-types",
  addons: "settings-addons",
  paymentMethods: "settings-payment-methods",
  actionsDirectory: "settings-actions",
  productAddons: "settings-product-addons",
  pays: "pays",
  reports: "reports",
  users: "users",
  userTypes: "user-types",
  venueNumbers: "venue-numbers",
  availabilityCalendar: "availability-calendar",
  settings: "settings",
  settingsUsers: "settings-users",
  settingsUserTypes: "settings-user-types",
  settingsPages: "settings-pages",
  settingsModules: "settings-modules",
  settingsPermissions: "settings-permissions",
  settingsPagePermissions: "settings-permissions-pages",
  settingsModulePermissions: "settings-permissions-modules",
  settingsProducts: "settings-products",
  settingsProductTypes: "settings-product-types",
  settingsAddons: "settings-addons",
  settingsProductAddons: "settings-product-addons",
  settingsPaymentMethods: "settings-payment-methods",
  settingsActions: "settings-actions",
  settingsChannels: "settings-channels",
};

export type PageSlugKey = keyof typeof PAGE_SLUGS;
