export type PhoneCodeOption = { value: string; label: string; iso2: string };

export const PHONE_CODE_OPTIONS: PhoneCodeOption[] = [
  { value: "+1", label: "+1 - American Samoa", iso2: "as" },
  { value: "+1", label: "+1 - Anguilla", iso2: "ai" },
  { value: "+1", label: "+1 - Antigua and Barbuda", iso2: "ag" },
  { value: "+1", label: "+1 - Bahamas", iso2: "bs" },
  { value: "+1", label: "+1 - Barbados", iso2: "bb" },
  { value: "+1", label: "+1 - Bermuda", iso2: "bm" },
  { value: "+1", label: "+1 - British Virgin Islands", iso2: "vg" },
  { value: "+1", label: "+1 - Canada", iso2: "ca" },
  { value: "+1", label: "+1 - Cayman Islands", iso2: "ky" },
  { value: "+1", label: "+1 - Dominica", iso2: "dm" },
  { value: "+1", label: "+1 - Dominican Republic", iso2: "do" },
  { value: "+1", label: "+1 - Grenada", iso2: "gd" },
  { value: "+1", label: "+1 - Guam", iso2: "gu" },
  { value: "+1", label: "+1 - Jamaica", iso2: "jm" },
  { value: "+1", label: "+1 - Montserrat", iso2: "ms" },
  { value: "+1", label: "+1 - Northern Mariana Islands", iso2: "mp" },
  { value: "+1", label: "+1 - Puerto Rico", iso2: "pr" },
  { value: "+1", label: "+1 - Saint Kitts and Nevis", iso2: "kn" },
  { value: "+1", label: "+1 - Saint Lucia", iso2: "lc" },
  { value: "+1", label: "+1 - Saint Vincent and the Grenadines", iso2: "vc" },
  { value: "+1", label: "+1 - Sint Maarten", iso2: "sx" },
  { value: "+1", label: "+1 - Trinidad and Tobago", iso2: "tt" },
  { value: "+1", label: "+1 - Turks and Caicos Islands", iso2: "tc" },
  { value: "+1", label: "+1 - United States", iso2: "us" },
  { value: "+1", label: "+1 - United States Virgin Islands", iso2: "vi" },
  { value: "+20", label: "+20 - Egypt", iso2: "eg" },
  { value: "+211", label: "+211 - South Sudan", iso2: "ss" },
  { value: "+212", label: "+212 - Morocco", iso2: "ma" },
  { value: "+212", label: "+212 - Western Sahara", iso2: "eh" },
  { value: "+213", label: "+213 - Algeria", iso2: "dz" },
  { value: "+216", label: "+216 - Tunisia", iso2: "tn" },
  { value: "+218", label: "+218 - Libya", iso2: "ly" },
  { value: "+220", label: "+220 - Gambia", iso2: "gm" },
  { value: "+221", label: "+221 - Senegal", iso2: "sn" },
  { value: "+222", label: "+222 - Mauritania", iso2: "mr" },
  { value: "+223", label: "+223 - Mali", iso2: "ml" },
  { value: "+224", label: "+224 - Guinea", iso2: "gn" },
  { value: "+225", label: "+225 - Ivory Coast", iso2: "ci" },
  { value: "+226", label: "+226 - Burkina Faso", iso2: "bf" },
  { value: "+227", label: "+227 - Niger", iso2: "ne" },
  { value: "+228", label: "+228 - Togo", iso2: "tg" },
  { value: "+229", label: "+229 - Benin", iso2: "bj" },
  { value: "+230", label: "+230 - Mauritius", iso2: "mu" },
  { value: "+231", label: "+231 - Liberia", iso2: "lr" },
  { value: "+232", label: "+232 - Sierra Leone", iso2: "sl" },
  { value: "+233", label: "+233 - Ghana", iso2: "gh" },
  { value: "+234", label: "+234 - Nigeria", iso2: "ng" },
  { value: "+235", label: "+235 - Chad", iso2: "td" },
  { value: "+236", label: "+236 - Central African Republic", iso2: "cf" },
  { value: "+237", label: "+237 - Cameroon", iso2: "cm" },
  { value: "+238", label: "+238 - Cape Verde", iso2: "cv" },
  { value: "+239", label: "+239 - São Tomé and Príncipe", iso2: "st" },
  { value: "+240", label: "+240 - Equatorial Guinea", iso2: "gq" },
  { value: "+241", label: "+241 - Gabon", iso2: "ga" },
  { value: "+242", label: "+242 - Republic of the Congo", iso2: "cg" },
  { value: "+243", label: "+243 - DR Congo", iso2: "cd" },
  { value: "+244", label: "+244 - Angola", iso2: "ao" },
  { value: "+245", label: "+245 - Guinea-Bissau", iso2: "gw" },
  { value: "+246", label: "+246 - British Indian Ocean Territory", iso2: "io" },
  { value: "+247", label: "+247 - Ascension Island", iso2: "ac" },
  { value: "+248", label: "+248 - Seychelles", iso2: "sc" },
  { value: "+249", label: "+249 - Sudan", iso2: "sd" },
  { value: "+250", label: "+250 - Rwanda", iso2: "rw" },
  { value: "+251", label: "+251 - Ethiopia", iso2: "et" },
  { value: "+252", label: "+252 - Somalia", iso2: "so" },
  { value: "+253", label: "+253 - Djibouti", iso2: "dj" },
  { value: "+254", label: "+254 - Kenya", iso2: "ke" },
  { value: "+255", label: "+255 - Tanzania", iso2: "tz" },
  { value: "+256", label: "+256 - Uganda", iso2: "ug" },
  { value: "+257", label: "+257 - Burundi", iso2: "bi" },
  { value: "+258", label: "+258 - Mozambique", iso2: "mz" },
  { value: "+260", label: "+260 - Zambia", iso2: "zm" },
  { value: "+261", label: "+261 - Madagascar", iso2: "mg" },
  { value: "+262", label: "+262 - Mayotte", iso2: "yt" },
  { value: "+262", label: "+262 - Réunion", iso2: "re" },
  { value: "+263", label: "+263 - Zimbabwe", iso2: "zw" },
  { value: "+264", label: "+264 - Namibia", iso2: "na" },
  { value: "+265", label: "+265 - Malawi", iso2: "mw" },
  { value: "+266", label: "+266 - Lesotho", iso2: "ls" },
  { value: "+267", label: "+267 - Botswana", iso2: "bw" },
  { value: "+268", label: "+268 - Eswatini", iso2: "sz" },
  { value: "+269", label: "+269 - Comoros", iso2: "km" },
  { value: "+27", label: "+27 - South Africa", iso2: "za" },
  { value: "+290", label: "+290 - Saint Helena, Ascension and Tristan da Cunha", iso2: "sh" },
  { value: "+291", label: "+291 - Eritrea", iso2: "er" },
  { value: "+297", label: "+297 - Aruba", iso2: "aw" },
  { value: "+298", label: "+298 - Faroe Islands", iso2: "fo" },
  { value: "+299", label: "+299 - Greenland", iso2: "gl" },
  { value: "+30", label: "+30 - Greece", iso2: "gr" },
  { value: "+31", label: "+31 - Netherlands", iso2: "nl" },
  { value: "+32", label: "+32 - Belgium", iso2: "be" },
  { value: "+33", label: "+33 - France", iso2: "fr" },
  { value: "+34", label: "+34 - Spain", iso2: "es" },
  { value: "+350", label: "+350 - Gibraltar", iso2: "gi" },
  { value: "+351", label: "+351 - Portugal", iso2: "pt" },
  { value: "+352", label: "+352 - Luxembourg", iso2: "lu" },
  { value: "+353", label: "+353 - Ireland", iso2: "ie" },
  { value: "+354", label: "+354 - Iceland", iso2: "is" },
  { value: "+355", label: "+355 - Albania", iso2: "al" },
  { value: "+356", label: "+356 - Malta", iso2: "mt" },
  { value: "+357", label: "+357 - Cyprus", iso2: "cy" },
  { value: "+358", label: "+358 - Finland", iso2: "fi" },
  { value: "+358", label: "+358 - Åland Islands", iso2: "ax" },
  { value: "+359", label: "+359 - Bulgaria", iso2: "bg" },
  { value: "+36", label: "+36 - Hungary", iso2: "hu" },
  { value: "+370", label: "+370 - Lithuania", iso2: "lt" },
  { value: "+371", label: "+371 - Latvia", iso2: "lv" },
  { value: "+372", label: "+372 - Estonia", iso2: "ee" },
  { value: "+373", label: "+373 - Moldova", iso2: "md" },
  { value: "+374", label: "+374 - Armenia", iso2: "am" },
  { value: "+375", label: "+375 - Belarus", iso2: "by" },
  { value: "+376", label: "+376 - Andorra", iso2: "ad" },
  { value: "+377", label: "+377 - Monaco", iso2: "mc" },
  { value: "+378", label: "+378 - San Marino", iso2: "sm" },
  { value: "+380", label: "+380 - Ukraine", iso2: "ua" },
  { value: "+381", label: "+381 - Serbia", iso2: "rs" },
  { value: "+382", label: "+382 - Montenegro", iso2: "me" },
  { value: "+383", label: "+383 - Kosovo", iso2: "xk" },
  { value: "+385", label: "+385 - Croatia", iso2: "hr" },
  { value: "+386", label: "+386 - Slovenia", iso2: "si" },
  { value: "+387", label: "+387 - Bosnia and Herzegovina", iso2: "ba" },
  { value: "+389", label: "+389 - North Macedonia", iso2: "mk" },
  { value: "+39", label: "+39 - Italy", iso2: "it" },
  { value: "+39", label: "+39 - Vatican City", iso2: "va" },
  { value: "+40", label: "+40 - Romania", iso2: "ro" },
  { value: "+41", label: "+41 - Switzerland", iso2: "ch" },
  { value: "+420", label: "+420 - Czechia", iso2: "cz" },
  { value: "+421", label: "+421 - Slovakia", iso2: "sk" },
  { value: "+423", label: "+423 - Liechtenstein", iso2: "li" },
  { value: "+43", label: "+43 - Austria", iso2: "at" },
  { value: "+44", label: "+44 - Guernsey", iso2: "gg" },
  { value: "+44", label: "+44 - Isle of Man", iso2: "im" },
  { value: "+44", label: "+44 - Jersey", iso2: "je" },
  { value: "+44", label: "+44 - United Kingdom", iso2: "gb" },
  { value: "+45", label: "+45 - Denmark", iso2: "dk" },
  { value: "+46", label: "+46 - Sweden", iso2: "se" },
  { value: "+47", label: "+47 - Norway", iso2: "no" },
  { value: "+47", label: "+47 - Svalbard and Jan Mayen", iso2: "sj" },
  { value: "+48", label: "+48 - Poland", iso2: "pl" },
  { value: "+49", label: "+49 - Germany", iso2: "de" },
  { value: "+500", label: "+500 - Falkland Islands", iso2: "fk" },
  { value: "+501", label: "+501 - Belize", iso2: "bz" },
  { value: "+502", label: "+502 - Guatemala", iso2: "gt" },
  { value: "+503", label: "+503 - El Salvador", iso2: "sv" },
  { value: "+504", label: "+504 - Honduras", iso2: "hn" },
  { value: "+505", label: "+505 - Nicaragua", iso2: "ni" },
  { value: "+506", label: "+506 - Costa Rica", iso2: "cr" },
  { value: "+507", label: "+507 - Panama", iso2: "pa" },
  { value: "+508", label: "+508 - Saint Pierre and Miquelon", iso2: "pm" },
  { value: "+509", label: "+509 - Haiti", iso2: "ht" },
  { value: "+51", label: "+51 - Peru", iso2: "pe" },
  { value: "+52", label: "+52 - Mexico", iso2: "mx" },
  { value: "+53", label: "+53 - Cuba", iso2: "cu" },
  { value: "+54", label: "+54 - Argentina", iso2: "ar" },
  { value: "+55", label: "+55 - Brazil", iso2: "br" },
  { value: "+56", label: "+56 - Chile", iso2: "cl" },
  { value: "+57", label: "+57 - Colombia", iso2: "co" },
  { value: "+58", label: "+58 - Venezuela", iso2: "ve" },
  { value: "+590", label: "+590 - Guadeloupe", iso2: "gp" },
  { value: "+590", label: "+590 - Saint Barthélemy", iso2: "bl" },
  { value: "+590", label: "+590 - Saint Martin", iso2: "mf" },
  { value: "+591", label: "+591 - Bolivia", iso2: "bo" },
  { value: "+592", label: "+592 - Guyana", iso2: "gy" },
  { value: "+593", label: "+593 - Ecuador", iso2: "ec" },
  { value: "+594", label: "+594 - French Guiana", iso2: "gf" },
  { value: "+595", label: "+595 - Paraguay", iso2: "py" },
  { value: "+596", label: "+596 - Martinique", iso2: "mq" },
  { value: "+597", label: "+597 - Suriname", iso2: "sr" },
  { value: "+598", label: "+598 - Uruguay", iso2: "uy" },
  { value: "+599", label: "+599 - Caribbean Netherlands", iso2: "bq" },
  { value: "+599", label: "+599 - Curaçao", iso2: "cw" },
  { value: "+60", label: "+60 - Malaysia", iso2: "my" },
  { value: "+61", label: "+61 - Australia", iso2: "au" },
  { value: "+61", label: "+61 - Christmas Island", iso2: "cx" },
  { value: "+61", label: "+61 - Cocos (Keeling) Islands", iso2: "cc" },
  { value: "+62", label: "+62 - Indonesia", iso2: "id" },
  { value: "+63", label: "+63 - Philippines", iso2: "ph" },
  { value: "+64", label: "+64 - New Zealand", iso2: "nz" },
  { value: "+65", label: "+65 - Singapore", iso2: "sg" },
  { value: "+66", label: "+66 - Thailand", iso2: "th" },
  { value: "+670", label: "+670 - Timor-Leste", iso2: "tl" },
  { value: "+672", label: "+672 - Norfolk Island", iso2: "nf" },
  { value: "+673", label: "+673 - Brunei", iso2: "bn" },
  { value: "+674", label: "+674 - Nauru", iso2: "nr" },
  { value: "+675", label: "+675 - Papua New Guinea", iso2: "pg" },
  { value: "+676", label: "+676 - Tonga", iso2: "to" },
  { value: "+677", label: "+677 - Solomon Islands", iso2: "sb" },
  { value: "+678", label: "+678 - Vanuatu", iso2: "vu" },
  { value: "+679", label: "+679 - Fiji", iso2: "fj" },
  { value: "+680", label: "+680 - Palau", iso2: "pw" },
  { value: "+681", label: "+681 - Wallis and Futuna", iso2: "wf" },
  { value: "+682", label: "+682 - Cook Islands", iso2: "ck" },
  { value: "+683", label: "+683 - Niue", iso2: "nu" },
  { value: "+685", label: "+685 - Samoa", iso2: "ws" },
  { value: "+686", label: "+686 - Kiribati", iso2: "ki" },
  { value: "+687", label: "+687 - New Caledonia", iso2: "nc" },
  { value: "+688", label: "+688 - Tuvalu", iso2: "tv" },
  { value: "+689", label: "+689 - French Polynesia", iso2: "pf" },
  { value: "+690", label: "+690 - Tokelau", iso2: "tk" },
  { value: "+691", label: "+691 - Micronesia", iso2: "fm" },
  { value: "+692", label: "+692 - Marshall Islands", iso2: "mh" },
  { value: "+7", label: "+7 - Kazakhstan", iso2: "kz" },
  { value: "+7", label: "+7 - Russia", iso2: "ru" },
  { value: "+81", label: "+81 - Japan", iso2: "jp" },
  { value: "+82", label: "+82 - South Korea", iso2: "kr" },
  { value: "+84", label: "+84 - Vietnam", iso2: "vn" },
  { value: "+850", label: "+850 - North Korea", iso2: "kp" },
  { value: "+852", label: "+852 - Hong Kong", iso2: "hk" },
  { value: "+853", label: "+853 - Macau", iso2: "mo" },
  { value: "+855", label: "+855 - Cambodia", iso2: "kh" },
  { value: "+856", label: "+856 - Laos", iso2: "la" },
  { value: "+86", label: "+86 - China", iso2: "cn" },
  { value: "+880", label: "+880 - Bangladesh", iso2: "bd" },
  { value: "+886", label: "+886 - Taiwan", iso2: "tw" },
  { value: "+90", label: "+90 - Turkey", iso2: "tr" },
  { value: "+91", label: "+91 - India", iso2: "in" },
  { value: "+92", label: "+92 - Pakistan", iso2: "pk" },
  { value: "+93", label: "+93 - Afghanistan", iso2: "af" },
  { value: "+94", label: "+94 - Sri Lanka", iso2: "lk" },
  { value: "+95", label: "+95 - Myanmar", iso2: "mm" },
  { value: "+960", label: "+960 - Maldives", iso2: "mv" },
  { value: "+961", label: "+961 - Lebanon", iso2: "lb" },
  { value: "+962", label: "+962 - Jordan", iso2: "jo" },
  { value: "+963", label: "+963 - Syria", iso2: "sy" },
  { value: "+964", label: "+964 - Iraq", iso2: "iq" },
  { value: "+965", label: "+965 - Kuwait", iso2: "kw" },
  { value: "+966", label: "+966 - Saudi Arabia", iso2: "sa" },
  { value: "+967", label: "+967 - Yemen", iso2: "ye" },
  { value: "+968", label: "+968 - Oman", iso2: "om" },
  { value: "+970", label: "+970 - Palestine", iso2: "ps" },
  { value: "+971", label: "+971 - United Arab Emirates", iso2: "ae" },
  { value: "+972", label: "+972 - Israel", iso2: "il" },
  { value: "+973", label: "+973 - Bahrain", iso2: "bh" },
  { value: "+974", label: "+974 - Qatar", iso2: "qa" },
  { value: "+975", label: "+975 - Bhutan", iso2: "bt" },
  { value: "+976", label: "+976 - Mongolia", iso2: "mn" },
  { value: "+977", label: "+977 - Nepal", iso2: "np" },
  { value: "+98", label: "+98 - Iran", iso2: "ir" },
  { value: "+992", label: "+992 - Tajikistan", iso2: "tj" },
  { value: "+993", label: "+993 - Turkmenistan", iso2: "tm" },
  { value: "+994", label: "+994 - Azerbaijan", iso2: "az" },
  { value: "+995", label: "+995 - Georgia", iso2: "ge" },
  { value: "+996", label: "+996 - Kyrgyzstan", iso2: "kg" },
  { value: "+998", label: "+998 - Uzbekistan", iso2: "uz" },
];


export const DEFAULT_PHONE_CODE = "+48";

export const PHONE_CODE_LOOKUP = PHONE_CODE_OPTIONS.reduce<Record<string, PhoneCodeOption>>((acc, option) => {
  acc[option.value] = option;
  return acc;
}, {});


export const PHONE_CODE_VALUES_DESC = PHONE_CODE_OPTIONS.map((option) => option.value).sort((a, b) => b.length - a.length);
