export type ConfigValueType = 'string' | 'number' | 'boolean' | 'enum' | 'json';

export type ConfigDefinition = {
  key: string;
  label: string;
  description?: string;
  category: string;
  valueType: ConfigValueType;
  defaultValue: string | number | boolean | null;
  isSecret?: boolean;
  isEditable?: boolean;
  impact?: 'low' | 'medium' | 'high';
  options?: string[];
  validation?: Record<string, unknown>;
};

export const CONFIG_DEFINITIONS: ConfigDefinition[] = [
  {
    key: 'SCHED_TZ',
    label: 'Scheduling timezone',
    description: 'Timezone used for schedule dates and notifications.',
    category: 'Scheduling',
    valueType: 'string',
    defaultValue: 'Europe/Warsaw',
    validation: { required: true, format: 'timezone' },
  },
  {
    key: 'SCHED_LOCK_DAY',
    label: 'Schedule lock day',
    description: 'Day of week (0=Sun..6=Sat) when schedules are locked.',
    category: 'Scheduling',
    valueType: 'number',
    defaultValue: 0,
    validation: { min: 0, max: 6 },
  },
  {
    key: 'SCHED_LOCK_HOUR',
    label: 'Schedule lock hour',
    description: 'Hour of day (0-23) to lock schedules.',
    category: 'Scheduling',
    valueType: 'number',
    defaultValue: 18,
    validation: { min: 0, max: 23 },
  },
  {
    key: 'SCHED_REMINDER1_DAY',
    label: 'Reminder 1 day',
    description: 'Day of week (0=Sun..6=Sat) for the first scheduling reminder.',
    category: 'Scheduling',
    valueType: 'number',
    defaultValue: 6,
    validation: { min: 0, max: 6 },
  },
  {
    key: 'SCHED_REMINDER1_HOUR',
    label: 'Reminder 1 hour',
    description: 'Hour (0-23) for the first scheduling reminder.',
    category: 'Scheduling',
    valueType: 'number',
    defaultValue: 18,
    validation: { min: 0, max: 23 },
  },
  {
    key: 'SCHED_REMINDER2_DAY',
    label: 'Reminder 2 day',
    description: 'Day of week (0=Sun..6=Sat) for the second scheduling reminder.',
    category: 'Scheduling',
    valueType: 'number',
    defaultValue: 0,
    validation: { min: 0, max: 6 },
  },
  {
    key: 'SCHED_REMINDER2_HOUR',
    label: 'Reminder 2 hour',
    description: 'Hour (0-23) for the second scheduling reminder.',
    category: 'Scheduling',
    valueType: 'number',
    defaultValue: 12,
    validation: { min: 0, max: 23 },
  },
  {
    key: 'BOOKING_GMAIL_QUERY',
    label: 'Booking Gmail query',
    description: 'Query used to fetch booking-related emails.',
    category: 'Booking Email Ingestion',
    valueType: 'string',
    defaultValue:
      'in:anywhere (subject:(booking OR reservation OR cancel OR cancellation OR "new order" OR "booking detail change" OR rebooked) OR from:(ecwid.com OR fareharbor.com OR freetour.com OR viator.com OR getyourguide.com OR xperiencepoland.com))',
    validation: { maxLength: 2000 },
  },
  {
    key: 'BOOKING_GMAIL_BATCH_SIZE',
    label: 'Booking Gmail batch size',
    description: 'Maximum number of messages to fetch per poll.',
    category: 'Booking Email Ingestion',
    valueType: 'number',
    defaultValue: 20,
    validation: { min: 1, max: 200 },
  },
  {
    key: 'BOOKING_EMAIL_POLL_CRON',
    label: 'Booking email poll cron',
    description: 'Cron schedule for Gmail polling.',
    category: 'Booking Email Ingestion',
    valueType: 'string',
    defaultValue: '*/5 * * * *',
    validation: { format: 'cron' },
  },
  {
    key: 'BOOKING_EMAIL_POLL_TZ',
    label: 'Booking email poll timezone',
    description: 'Timezone used for the poll schedule.',
    category: 'Booking Email Ingestion',
    valueType: 'string',
    defaultValue: 'UTC',
    validation: { format: 'timezone' },
  },
  {
    key: 'BOOKING_PARSER_TIMEZONE',
    label: 'Booking parser timezone',
    description: 'Default timezone for booking email parsers.',
    category: 'Booking Parsers',
    valueType: 'string',
    defaultValue: 'Europe/Warsaw',
    validation: { format: 'timezone' },
  },
  {
    key: 'AIRBNB_TIMEZONE',
    label: 'Airbnb parser timezone',
    description: 'Override timezone for Airbnb booking emails.',
    category: 'Booking Parsers',
    valueType: 'string',
    defaultValue: null,
    validation: { format: 'timezone' },
  },
  {
    key: 'ECWID_TIMEZONE',
    label: 'Ecwid parser timezone',
    description: 'Override timezone for Ecwid booking emails.',
    category: 'Booking Parsers',
    valueType: 'string',
    defaultValue: null,
    validation: { format: 'timezone' },
  },
  {
    key: 'FAREHARBOR_TIMEZONE',
    label: 'FareHarbor parser timezone',
    description: 'Override timezone for FareHarbor booking emails.',
    category: 'Booking Parsers',
    valueType: 'string',
    defaultValue: null,
    validation: { format: 'timezone' },
  },
  {
    key: 'FREETOUR_TIMEZONE',
    label: 'FreeTour parser timezone',
    description: 'Override timezone for FreeTour booking emails.',
    category: 'Booking Parsers',
    valueType: 'string',
    defaultValue: null,
    validation: { format: 'timezone' },
  },
  {
    key: 'GETYOURGUIDE_TIMEZONE',
    label: 'GetYourGuide parser timezone',
    description: 'Override timezone for GetYourGuide booking emails.',
    category: 'Booking Parsers',
    valueType: 'string',
    defaultValue: null,
    validation: { format: 'timezone' },
  },
  {
    key: 'VIATOR_TIMEZONE',
    label: 'Viator parser timezone',
    description: 'Override timezone for Viator booking emails.',
    category: 'Booking Parsers',
    valueType: 'string',
    defaultValue: null,
    validation: { format: 'timezone' },
  },
  {
    key: 'XPERIENCEPOLAND_TIMEZONE',
    label: 'Xperience Poland parser timezone',
    description: 'Override timezone for Xperience Poland booking emails.',
    category: 'Booking Parsers',
    valueType: 'string',
    defaultValue: null,
    validation: { format: 'timezone' },
  },
  {
    key: 'GOOGLE_CLIENT_ID',
    label: 'Google client ID',
    description: 'OAuth client ID for Google APIs.',
    category: 'Google API',
    valueType: 'string',
    defaultValue: null,
    isSecret: true,
  },
  {
    key: 'GOOGLE_CLIENT_SECRET',
    label: 'Google client secret',
    description: 'OAuth client secret for Google APIs.',
    category: 'Google API',
    valueType: 'string',
    defaultValue: null,
    isSecret: true,
  },
  {
    key: 'GOOGLE_REFRESH_TOKEN',
    label: 'Google refresh token',
    description: 'OAuth refresh token used for Gmail/Drive access.',
    category: 'Google API',
    valueType: 'string',
    defaultValue: null,
    isSecret: true,
  },
  {
    key: 'GOOGLE_DRIVE_SCHEDULES_PARENT_ID',
    label: 'Google Drive schedules folder',
    description: 'Parent folder ID where schedules are uploaded.',
    category: 'Google API',
    valueType: 'string',
    defaultValue: null,
  },
  {
    key: 'GOOGLE_CLIENT_EMAIL',
    label: 'Google service account email',
    description: 'Service account client email for Google APIs.',
    category: 'Google Service Account',
    valueType: 'string',
    defaultValue: null,
    isSecret: true,
  },
  {
    key: 'GOOGLE_PRIVATE_KEY',
    label: 'Google service account private key',
    description: 'Service account private key for Google APIs.',
    category: 'Google Service Account',
    valueType: 'string',
    defaultValue: null,
    isSecret: true,
  },
  {
    key: 'SMTP_HOST',
    label: 'SMTP host',
    description: 'SMTP server hostname for outbound email.',
    category: 'SMTP',
    valueType: 'string',
    defaultValue: null,
  },
  {
    key: 'SMTP_PORT',
    label: 'SMTP port',
    description: 'SMTP port for outbound email.',
    category: 'SMTP',
    valueType: 'number',
    defaultValue: null,
    validation: { min: 1, max: 65535 },
  },
  {
    key: 'SMTP_USER',
    label: 'SMTP username',
    description: 'SMTP user for outbound email.',
    category: 'SMTP',
    valueType: 'string',
    defaultValue: null,
    isSecret: true,
  },
  {
    key: 'SMTP_PASS',
    label: 'SMTP password',
    description: 'SMTP password for outbound email.',
    category: 'SMTP',
    valueType: 'string',
    defaultValue: null,
    isSecret: true,
  },
  {
    key: 'SMTP_FROM',
    label: 'SMTP from address',
    description: 'Default From address for outbound email.',
    category: 'SMTP',
    valueType: 'string',
    defaultValue: null,
  },
  {
    key: 'ECWID_STORE_ID',
    label: 'ECWID store ID',
    description: 'Store ID for the ECWID integration.',
    category: 'ECWID',
    valueType: 'string',
    defaultValue: null,
  },
  {
    key: 'ECWID_BASE_URL',
    label: 'ECWID base URL',
    description: 'Base URL for the ECWID API.',
    category: 'ECWID',
    valueType: 'string',
    defaultValue: 'https://app.ecwid.com/api/v3',
  },
  {
    key: 'ECWID_API_TOKEN',
    label: 'ECWID API token',
    description: 'API token for the ECWID integration.',
    category: 'ECWID',
    valueType: 'string',
    defaultValue: null,
    isSecret: true,
  },
  {
    key: 'ECWID_STORE_TIMEZONE',
    label: 'ECWID store timezone',
    description: 'Timezone used for ECWID order timestamps.',
    category: 'ECWID',
    valueType: 'string',
    defaultValue: 'Europe/Warsaw',
    validation: { format: 'timezone' },
  },
  {
    key: 'STRIPE_SECRET_KEY',
    label: 'Stripe secret key',
    description: 'Secret key used to authenticate Stripe API requests.',
    category: 'Stripe',
    valueType: 'string',
    defaultValue: null,
    isSecret: true,
  },
  {
    key: 'DB_BACKUP_STORAGE',
    label: 'DB backup storage',
    description: 'Storage backend for backups.',
    category: 'Backups',
    valueType: 'enum',
    defaultValue: 'drive',
    options: ['local', 'drive'],
  },
  {
    key: 'DB_BACKUP_DRIVE_FOLDER',
    label: 'DB backup drive folder',
    description: 'Root folder name for Drive backups.',
    category: 'Backups',
    valueType: 'string',
    defaultValue: 'Database Backups',
  },
  {
    key: 'DB_BACKUP_CRON',
    label: 'DB backup cron',
    description: 'Cron schedule for automated database backups.',
    category: 'Backups',
    valueType: 'string',
    defaultValue: '0 6 * * *',
    validation: { format: 'cron' },
  },
  {
    key: 'DB_BACKUP_TZ',
    label: 'DB backup timezone',
    description: 'Timezone used for backup scheduling.',
    category: 'Backups',
    valueType: 'string',
    defaultValue: 'UTC',
    validation: { format: 'timezone' },
  },
  {
    key: 'DB_BACKUP_DIRECTORY',
    label: 'DB backup directory',
    description: 'Local directory for database backups.',
    category: 'Backups',
    valueType: 'string',
    defaultValue: '/home/postgres/backups',
  },
  {
    key: 'DB_BACKUP_SCRIPT',
    label: 'DB backup script path',
    description: 'Path to the backup script executable.',
    category: 'Backups',
    valueType: 'string',
    defaultValue: '/home/postgres/backup.sh',
  },
  {
    key: 'DB_BACKUP_ROLE',
    label: 'DB backup role',
    description: 'Role used when restoring backups.',
    category: 'Backups',
    valueType: 'string',
    defaultValue: null,
  },
  {
    key: 'PG_RESTORE_BIN',
    label: 'pg_restore binary',
    description: 'Path to the pg_restore binary.',
    category: 'Backups',
    valueType: 'string',
    defaultValue: 'pg_restore',
  },
  {
    key: 'PSQL_BIN',
    label: 'psql binary',
    description: 'Path to the psql binary.',
    category: 'Backups',
    valueType: 'string',
    defaultValue: 'psql',
  },
  {
    key: 'FINANCE_BASE_CURRENCY',
    label: 'Finance base currency',
    description: 'Default currency code used in finance reports.',
    category: 'Finance',
    valueType: 'string',
    defaultValue: 'PLN',
    validation: { maxLength: 3 },
  },
  {
    key: 'FINANCE_AUTOMATION_USER_ID',
    label: 'Finance automation user',
    description: 'User ID used by finance background jobs.',
    category: 'Finance',
    valueType: 'number',
    defaultValue: 1,
  },
  {
    key: 'FINANCE_RECURRING_POLL_MS',
    label: 'Finance recurring poll interval (ms)',
    description: 'Polling interval for recurring finance jobs.',
    category: 'Finance',
    valueType: 'number',
    defaultValue: 900000,
    validation: { min: 60000 },
  },
  {
    key: 'STAFF_LEDGER_START_DATE',
    label: 'Staff ledger start date',
    description: 'Start date for staff payout ledger calculations (YYYY-MM-DD).',
    category: 'Finance',
    valueType: 'string',
    defaultValue: '2025-10-01',
  },
  {
    key: 'PAYOUT_LEDGER_START',
    label: 'Payout ledger start date',
    description: 'Legacy fallback for staff ledger start date (YYYY-MM-DD).',
    category: 'Finance',
    valueType: 'string',
    defaultValue: '2025-10-01',
  },
  {
    key: 'VENUE_LEDGER_START_DATE',
    label: 'Venue ledger start date',
    description: 'Start date for venue ledger calculations (YYYY-MM-DD).',
    category: 'Finance',
    valueType: 'string',
    defaultValue: '2025-10-01',
  },
  {
    key: 'VENUE_COMP_LEDGER_START',
    label: 'Venue compensation ledger start date',
    description: 'Legacy fallback for venue ledger start date (YYYY-MM-DD).',
    category: 'Finance',
    valueType: 'string',
    defaultValue: '2025-10-01',
  },
  {
    key: 'REPORT_CACHE_TTL_SECONDS',
    label: 'Report cache TTL (seconds)',
    description: 'TTL for cached report query results.',
    category: 'Reporting',
    valueType: 'number',
    defaultValue: 300,
    validation: { min: 60 },
  },
  {
    key: 'NIGHT_REPORT_UPLOAD_DIR',
    label: 'Night report upload directory',
    description: 'Local directory for night report uploads.',
    category: 'Storage',
    valueType: 'string',
    defaultValue: null,
  },
  {
    key: 'PROFILE_PHOTO_UPLOAD_DIR',
    label: 'Profile photo upload directory',
    description: 'Local directory for profile photo uploads.',
    category: 'Storage',
    valueType: 'string',
    defaultValue: null,
  },
  {
    key: 'PUPPETEER_HEADLESS',
    label: 'Puppeteer headless mode',
    description: 'Controls headless mode for schedule rendering (true, false, shell).',
    category: 'Scheduling',
    valueType: 'enum',
    defaultValue: 'true',
    options: ['true', 'false', 'shell'],
  },
  {
    key: 'TRIP_ADVISOR_LOCATION_ID',
    label: 'TripAdvisor location ID',
    description: 'Location ID used by the TripAdvisor scraper.',
    category: 'Review Scrapers',
    valueType: 'number',
    defaultValue: 2725527,
  },
  {
    key: 'TRIP_ADVISOR_PAGE_SIZE',
    label: 'TripAdvisor page size',
    description: 'Page size used by the TripAdvisor scraper.',
    category: 'Review Scrapers',
    valueType: 'number',
    defaultValue: 20,
  },
  {
    key: 'TRIP_ADVISOR_LANGUAGE',
    label: 'TripAdvisor language',
    description: 'Language code for TripAdvisor requests.',
    category: 'Review Scrapers',
    valueType: 'string',
    defaultValue: 'en',
  },
  {
    key: 'TRIP_ADVISOR_COOKIE',
    label: 'TripAdvisor cookie',
    description: 'Cookie header used for TripAdvisor requests.',
    category: 'Review Scrapers',
    valueType: 'string',
    defaultValue: null,
    isSecret: true,
  },
  {
    key: 'TRIP_ADVISOR_REFERER',
    label: 'TripAdvisor referer',
    description: 'Referer header used for TripAdvisor requests.',
    category: 'Review Scrapers',
    valueType: 'string',
    defaultValue: null,
  },
  {
    key: 'GYG_REVIEWS_ENDPOINT',
    label: 'GetYourGuide reviews endpoint',
    description: 'Endpoint for GetYourGuide review blocks.',
    category: 'Review Scrapers',
    valueType: 'string',
    defaultValue:
      'https://travelers-api.getyourguide.com/user-interface/activity-details-page/blocks?ranking_uuid=2abbc102-010b-4c47-b440-376e2af70475',
  },
  {
    key: 'GYG_ACTIVITY_ID',
    label: 'GetYourGuide activity ID',
    description: 'Activity ID for GetYourGuide reviews.',
    category: 'Review Scrapers',
    valueType: 'number',
    defaultValue: 443425,
  },
  {
    key: 'GYG_RANKING_UUID',
    label: 'GetYourGuide ranking UUID',
    description: 'Ranking UUID for GetYourGuide reviews.',
    category: 'Review Scrapers',
    valueType: 'string',
    defaultValue: '2abbc102-010b-4c47-b440-376e2af70475',
  },
  {
    key: 'GYG_REVIEWS_LIMIT',
    label: 'GetYourGuide reviews limit',
    description: 'Maximum number of reviews returned by the scraper.',
    category: 'Review Scrapers',
    valueType: 'number',
    defaultValue: 30,
  },
  {
    key: 'GYG_PAGE_LIMIT',
    label: 'GetYourGuide page limit',
    description: 'Page size used by the GetYourGuide scraper.',
    category: 'Review Scrapers',
    valueType: 'number',
    defaultValue: 10,
  },
  {
    key: 'GYG_MIN_LIMIT',
    label: 'GetYourGuide minimum limit',
    description: 'Minimum number of reviews to request.',
    category: 'Review Scrapers',
    valueType: 'number',
    defaultValue: 20,
  },
  {
    key: 'GYG_MAX_LIMIT',
    label: 'GetYourGuide maximum limit',
    description: 'Maximum number of reviews to request.',
    category: 'Review Scrapers',
    valueType: 'number',
    defaultValue: 150,
  },
  {
    key: 'GYG_CACHE_TTL_MS',
    label: 'GetYourGuide cache TTL (ms)',
    description: 'Cache TTL for GetYourGuide reviews.',
    category: 'Review Scrapers',
    valueType: 'number',
    defaultValue: 300000,
  },
  {
    key: 'GYG_SESSION_URL',
    label: 'GetYourGuide session URL',
    description: 'URL used to prime GetYourGuide sessions.',
    category: 'Review Scrapers',
    valueType: 'string',
    defaultValue: 'https://www.getyourguide.com/',
  },
  {
    key: 'GYG_PRODUCT_URL',
    label: 'GetYourGuide product URL',
    description: 'Product URL used for GetYourGuide session priming.',
    category: 'Review Scrapers',
    valueType: 'string',
    defaultValue: 'https://www.getyourguide.com/krawl-through-krakow-pubcrawl-s264786/',
  },
  {
    key: 'GYG_USER_AGENT',
    label: 'GetYourGuide user agent',
    description: 'User agent used for GetYourGuide scraping.',
    category: 'Review Scrapers',
    valueType: 'string',
    defaultValue:
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36',
  },
  {
    key: 'DB_SYNC_ALTER',
    label: 'DB sync alter',
    description: 'Allow sequelize.sync to alter tables (use migrations instead).',
    category: 'Maintenance',
    valueType: 'boolean',
    defaultValue: false,
    impact: 'high',
  },
  {
    key: 'SKIP_DB_SYNC',
    label: 'Skip DB sync',
    description: 'Skip sequelize.sync at startup.',
    category: 'Maintenance',
    valueType: 'boolean',
    defaultValue: true,
    impact: 'high',
  },
  {
    key: 'SEED_ACCESS_CONTROL',
    label: 'Seed access control',
    description: 'Seed default access control entities at startup.',
    category: 'Maintenance',
    valueType: 'boolean',
    defaultValue: false,
    impact: 'medium',
  },
];

export const CONFIG_DEFINITION_MAP = new Map(CONFIG_DEFINITIONS.map((definition) => [definition.key, definition]));
